In [2]:
import pandas as pd
import numpy as np
import xlsxwriter as xl
import io
from xlsxwriter.utility import xl_col_to_name

In [5]:
pd.options.display.float_format = '{:.2f}'.format

In [6]:
sourceData = pd.read_excel(
    "C:/Auditor Valuation Framework/exccute.py/Profitability results from FY 2024 to FY 2025.xlsx",
    sheet_name="Detailed"
)
sourceData

,Business ID,Business Title,Type of Business,Underwriting Year,Cedent Name,Cedent Country,Reporting Unit1 Leaf Name,Broker Name,Insured Name,Insured Period Start,...,Detail Amount (Original),Detail Amount (Base),Retroceded Amt Base,Retained Amt Base,Main Class of Business,Class of Business,Registered Date,Closed Date,WS Registered By,WS Closed By
0,NPF1003A,CHEVRON NIGERIA LTD/ESCRAVOS GTL,Non-Prop Facultative,2023,NEM Insurance PLC Nigeria,Nigeria,Nigeria Office,Gallagher Reinsurance Brokers,CHEVRON NIGERIA LTD/ESCRAVOS GTL,2023-01-02,...,1751.75,1751.75,0.00,1751.75,Oil&Gas,All Risk Oil&Gas,2024-05-08 06:24:35,2024-05-08 09:20:25,Frances Nwogbe,Michael Adeyinka
1,NPF1003A,CHEVRON NIGERIA LTD/ESCRAVOS GTL,Non-Prop Facultative,2023,NEM Insurance PLC Nigeria,Nigeria,Nigeria Office,Gallagher Reinsurance Brokers,CHEVRON NIGERIA LTD/ESCRAVOS GTL,2023-01-02,...,-175.18,-175.18,0.00,-175.18,Oil&Gas,All Risk Oil&Gas,2024-05-08 06:24:35,2024-05-08 09:20:25,Frances Nwogbe,Michael Adeyinka
2,NPF1003A,CHEVRON NIGERIA LTD/ESCRAVOS GTL,Non-Prop Facultative,2023,NEM Insurance PLC Nigeria,Nigeria,Nigeria Office,Gallagher Reinsurance Brokers,CHEVRON NIGERIA LTD/ESCRAVOS GTL,2023-01-02,...,-262.76,-262.76,0.00,-262.76,Oil&Gas,All Risk Oil&Gas,2024-05-08 06:24:35,2024-05-08 09:20:25,Frances Nwogbe,Michael Adeyinka
3,NPF1003A,CHEVRON NIGERIA LTD/ESCRAVOS GTL,Non-Prop Facultative,2023,NEM Insurance PLC Nigeria,Nigeria,Nigeria Office,Gallagher Reinsurance Brokers,CHEVRON NIGERIA LTD/ESCRAVOS GTL,2023-01-02,...,623.27,623.27,0.00,623.27,Oil&Gas,All Risk Oil&Gas,2024-07-29 08:04:11,2024-07-29 08:05:30,Frances Nwogbe,Sandra Didiya Yakusak
4,NPF1003A,CHEVRON NIGERIA LTD/ESCRAVOS GTL,Non-Prop Facultative,2023,NEM Insurance PLC Nigeria,Nigeria,Nigeria Office,Gallagher Reinsurance Brokers,CHEVRON NIGERIA LTD/ESCRAVOS GTL,2023-01-02,...,-93.49,-93.49,0.00,-93.49,Oil&Gas,All Risk Oil&Gas,2024-07-29 08:04:11,2024-07-29 08:05:30,Frances Nwogbe,Sandra Didiya Yakusak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246254,PPT6391A,PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...,Proportional Treaty,2025,People and Partners Insurance Plc,Cambodia,Asia,NaN,NaN,2025-10-01,...,-280.38,-280.38,0.00,-280.38,Property,Fire (unspecified),2026-01-02 15:41:19,2026-01-02 15:51:26,Alusine Kamara,Alpha Koroma
246255,PPT6391A,PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...,Proportional Treaty,2025,People and Partners Insurance Plc,Cambodia,Asia,NaN,NaN,2025-10-01,...,-62.94,-62.94,0.00,-62.94,Property,Fire (unspecified),2026-01-02 15:41:19,2026-01-02 15:51:26,Alusine Kamara,Alpha Koroma
246256,PPT6391A,PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...,Proportional Treaty,2025,People and Partners Insurance Plc,Cambodia,Asia,NaN,NaN,2025-10-01,...,164.46,164.46,0.00,164.46,Property,Fire (unspecified),2026-01-02 15:49:08,2026-01-02 15:52:22,Alusine Kamara,Alpha Koroma
246257,PPT6391A,PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...,Proportional Treaty,2025,People and Partners Insurance Plc,Cambodia,Asia,NaN,NaN,2025-10-01,...,-40.29,-40.29,0.00,-40.29,Property,Fire (unspecified),2026-01-02 15:49:08,2026-01-02 15:52:22,Alusine Kamara,Alpha Koroma
246258,PPT6391A,PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...,Proportional Treaty,2025,People and Partners Insurance Plc,Cambodia,Asia,NaN,NaN,2025-10-01,...,-9.05,-9.05,0.00,-9.05,Property,Fire (unspecified),2026-01-02 15:49:08,2026-01-02 15:52:22,Alusine Kamara,Alpha Koroma

In [6]:
categoryHeader = "Reporting Unit1 Leaf Name"
codeHeader = "Entry Code"
dataFieldHeader = "Retained Amt Base"
grossDataFieldHeader = "Detail Amount (Base)"
netManagementExpenseRatio = 0.12
sheetName = "Detailed"  # Parameter for Excel sheet name

premiumCode = np.array([100,500])
claimCode = np.array([300,600,900])
commissionCode = np.array([200])

# Load data
sourceData = pd.read_excel(
    "C:/Auditor Valuation Framework/exccute.py/Profitability results from FY 2024 to FY 2025.xlsx",
    sheet_name=sheetName
)

filterItems = pd.unique(sourceData[categoryHeader].dropna())
sourceData[codeHeader] = sourceData[codeHeader].astype(str).str.strip()
sourceData[codeHeader] = pd.to_numeric(sourceData[codeHeader], errors="coerce")

resultTableDictionary = {
    categoryHeader:np.append(np.array(filterItems), "Total"),
    "Net Premium": np.array([]),
    "Net Incurred Claim": np.array([]),
    "Net Commission": np.array([]),
    "Net Technical Margin": np.array([]),
    "Loss Ratio": np.array([]),
    "Commission Ratio": np.array([]),
    "Net Management Expense Ratio": np.array([]),
    "Net Technical Margin Ratio": np.array([]),
    "Net Retro Expense Ratio": np.array([]),
    "Combined Ratio": np.array([])
}

grossPremiumSum = 0
grossPremiumSumArr = np.array([])
premiumTable = pd.DataFrame(columns=sourceData.columns)
claimTable = pd.DataFrame(columns=sourceData.columns)
commissionTable = pd.DataFrame(columns=sourceData.columns)

def ratioAnalysis():

    global grossPremiumSum, grossPremiumSumArr, premiumTable, claimTable, commissionTable

    for item in filterItems:
        print(item)
        filteredTable = sourceData[sourceData[categoryHeader] == item]
        
        premiumSum = 0
        grossPremiumSum = 0
        for code in premiumCode:
            premiumFilteredTable = filteredTable[(filteredTable[codeHeader] >= code) & (filteredTable[codeHeader] <= (code + 99))]
            premiumTable = pd.concat([premiumTable, premiumFilteredTable], ignore_index=True)
            premiumSum += np.sum(premiumFilteredTable[dataFieldHeader])
            grossPremiumSum += np.sum(premiumFilteredTable[grossDataFieldHeader])

        claimSum = 0
        for code in claimCode:
            claimFilteredTable = filteredTable[(filteredTable[codeHeader] >= code) & (filteredTable[codeHeader] <= (code + 99))]
            claimTable = pd.concat([claimTable,claimFilteredTable], ignore_index=True)
            claimSum += np.sum(claimFilteredTable[dataFieldHeader])

        commissionSum = 0
        for code in commissionCode:
            commissionFilteredTable = filteredTable[(filteredTable[codeHeader] >= code) & (filteredTable[codeHeader] <= (code + 99))]
            commissionTable = pd.concat([commissionTable, commissionFilteredTable], ignore_index=True)
            commissionSum += np.sum(commissionFilteredTable[dataFieldHeader])

        netTechnicalMargin = premiumSum + claimSum + commissionSum
        lossRatio = abs(claimSum / premiumSum) if premiumSum != 0 else 0
        commissionRatio = abs(commissionSum / premiumSum) if premiumSum != 0 else 0
        netManagementExpenseRatioLocal = netManagementExpenseRatio
        netTechnicalMarginRatio = abs(netTechnicalMargin/premiumSum) if premiumSum != 0 else 0
        netRetroExpenseRatio = 1 - premiumSum / grossPremiumSum if grossPremiumSum != 0 else 0
        combinedRatio = lossRatio + commissionRatio + netManagementExpenseRatio + netRetroExpenseRatio

        resultTableDictionary["Net Premium"]= np.append(resultTableDictionary["Net Premium"], premiumSum)
        resultTableDictionary["Net Incurred Claim"] = np.append(resultTableDictionary["Net Incurred Claim"], claimSum)
        resultTableDictionary["Net Commission"] = np.append(resultTableDictionary["Net Commission"], commissionSum)
        resultTableDictionary["Net Technical Margin"] = np.append(resultTableDictionary["Net Technical Margin"], netTechnicalMargin)
        resultTableDictionary["Loss Ratio"] = np.append(resultTableDictionary["Loss Ratio"],lossRatio)
        resultTableDictionary["Commission Ratio"] = np.append(resultTableDictionary["Commission Ratio"], commissionRatio)
        resultTableDictionary["Net Management Expense Ratio"] = np.append(resultTableDictionary["Net Management Expense Ratio"], netManagementExpenseRatioLocal)
        resultTableDictionary["Net Technical Margin Ratio"] = np.append(resultTableDictionary["Net Technical Margin Ratio"], netTechnicalMarginRatio)
        resultTableDictionary["Net Retro Expense Ratio"]= np.append(resultTableDictionary["Net Retro Expense Ratio"], netRetroExpenseRatio)
        resultTableDictionary["Combined Ratio"] = np.append(resultTableDictionary["Combined Ratio"], combinedRatio)
        grossPremiumSumArr = np.append(grossPremiumSumArr,grossPremiumSum)

ratioAnalysis()

resultTableDictionary["Net Premium"]= np.append(resultTableDictionary["Net Premium"], np.sum(resultTableDictionary["Net Premium"]))
resultTableDictionary["Net Incurred Claim"]= np.append(resultTableDictionary["Net Incurred Claim"], np.sum(resultTableDictionary["Net Incurred Claim"]))
resultTableDictionary["Net Commission"]= np.append(resultTableDictionary["Net Commission"], np.sum(resultTableDictionary["Net Commission"]))
resultTableDictionary["Net Technical Margin"]= np.append(resultTableDictionary["Net Technical Margin"], np.sum(resultTableDictionary["Net Technical Margin"]))

resultTableDictionary["Loss Ratio"] = np.append(resultTableDictionary["Loss Ratio"],
                                               abs((resultTableDictionary["Net Incurred Claim"])[-1]
                                                   /(resultTableDictionary["Net Premium"])[-1]) )
resultTableDictionary["Commission Ratio"] = np.append(resultTableDictionary["Commission Ratio"],
                                               abs((resultTableDictionary["Net Commission"])[-1]
                                                   /(resultTableDictionary["Net Premium"])[-1]) )
resultTableDictionary["Net Management Expense Ratio"] = np.append(resultTableDictionary["Net Management Expense Ratio"], netManagementExpenseRatio )
resultTableDictionary["Net Technical Margin Ratio"] = np.append(resultTableDictionary["Net Technical Margin Ratio"],
                                               abs((resultTableDictionary["Net Technical Margin"])[-1]
                                                   /(resultTableDictionary["Net Premium"])[-1]) )
resultTableDictionary["Net Retro Expense Ratio"] = np.append(resultTableDictionary["Net Retro Expense Ratio"],1 -
                                               abs((resultTableDictionary["Net Premium"])[-1]
                                                   /np.sum(grossPremiumSumArr)) )
resultTableDictionary["Combined Ratio"] = np.append(resultTableDictionary["Combined Ratio"],
                                                     resultTableDictionary["Loss Ratio"][-1] + resultTableDictionary["Commission Ratio"][-1] +\
                                                        resultTableDictionary["Net Management Expense Ratio"][-1] + resultTableDictionary["Net Retro Expense Ratio"][-1])


resultTable = pd.DataFrame(resultTableDictionary).reset_index(drop=True)

ratio_columns = [
    "Loss Ratio",
    "Commission Ratio",
    "Net Management Expense Ratio",
    "Net Technical Margin Ratio",
    "Net Retro Expense Ratio",
    "Combined Ratio"
]

name_columns = [
    "Net Premium",
    "Net Incurred Claim",
    "Net Commission",
    "Net Technical Margin"
]

resultTable[name_columns] = resultTable[name_columns].map(
    lambda x: f"({abs(x):,.2f})" if x < 0 else f"{x:,.2f}"
)

resultTable[ratio_columns] = resultTable[ratio_columns].map(lambda x: f"{x:.2%}")
print(premiumTable[dataFieldHeader].sum)
premiumTable

KeyboardInterrupt:

In [7]:
categoryHeader = "Reporting Unit1 Leaf Name"
codeHeader = "Entry Code"
dataFieldHeader = "Retained Amt Base"
grossDataFieldHeader = "Detail Amount (Base)"
netManagementExpenseRatio = 0.12

premiumCode = np.array([100,500])
claimCode = np.array([300,600,900])
commissionCode = np.array([200])


filterItems = pd.unique(sourceData[categoryHeader].dropna())
sourceData[codeHeader] = sourceData[codeHeader].astype(str).str.strip()
sourceData[codeHeader] = pd.to_numeric(sourceData[codeHeader], errors="coerce")



def premiumClaimCommissionTableConstruct():

    premiumTable = pd.DataFrame(columns=sourceData.columns)
    claimTable = pd.DataFrame(columns=sourceData.columns)
    commissionTable = pd.DataFrame(columns=sourceData.columns)
        

    for code in premiumCode:
        premiumFilteredTable = sourceData[(sourceData[codeHeader] >= code) & (sourceData[codeHeader] <= (code + 99))]
        premiumTable = pd.concat([premiumTable, premiumFilteredTable], ignore_index=True)

    for code in claimCode:
        claimFilteredTable = sourceData[(sourceData[codeHeader] >= code) & (sourceData[codeHeader] <= (code + 99))]
        claimTable = pd.concat([claimTable,claimFilteredTable], ignore_index=True)

    for code in commissionCode:
        commissionFilteredTable = sourceData[(sourceData[codeHeader] >= code) & (sourceData[codeHeader] <= (code + 99))]
        commissionTable = pd.concat([commissionTable, commissionFilteredTable], ignore_index=True)

    return({
        "premiumTable": premiumTable,
        "claimTable": claimTable,
        "commissionTable": commissionTable
    })

tableDict = premiumClaimCommissionTableConstruct()
tableDict

{'premiumTable':       Business ID                                     Business Title  \
 0        NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 1        NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 2        NPF1004A         TOTAL UPSTREAM NIGERIA LIMITED (AKPO FPSO)
 3        NPF1012A  INDORAMA ELEME PETROCHEMICALS/FERTILIZERS LIMITED
 4        NPF1016A             TOTAL UPSTREAM NIGERIA LIMITED (EGINA)
 ...           ...                                                ...
 85648    PPT6376A                               ZAYTOUNA/ GEN ACC SP
 85649    PPT6377A                              ZAYTOUNA/FIRE QS & SP
 85650    PPT6378A                              ZAYTOUNA/ ENG QS & SP
 85651    PPT6378A                              ZAYTOUNA/ ENG QS & SP
 85652    PPT6389A                       ARC/SERENITY SA/BOND SURPLUS

            Type of Business Underwriting Year  \
 0      Non-Prop Facultative              2023
 1      Non-Prop Facultative              2023
 2      Non-Prop Facultative              2023
 3      Non-Prop Facultative              2019
 4      Non-Prop Facultative              2023
 ...                     ...               ...
 85648   Proportional Treaty              2024
 85649   Proportional Treaty              2024
 85650   Proportional Treaty              2024
 85651   Proportional Treaty              2024
 85652   Proportional Treaty              2025

                                          Cedent Name Cedent Country  \
 0                          NEM Insurance PLC Nigeria        Nigeria
 1                          NEM Insurance PLC Nigeria        Nigeria
 2                          NEM Insurance PLC Nigeria        Nigeria
 3                              AXA MANSARD INSURANCE        Nigeria
 4                          NEM Insurance PLC Nigeria        Nigeria
 ...                                              ...            ...
 85648                     Zaytouna Insurance Company          Libya
 85649                     Zaytouna Insurance Company          Libya
 85650                     Zaytouna Insurance Company          Libya
 85651                     Zaytouna Insurance Company          Libya
 85652  Serenity S.A.                                    Ivory coast

       Reporting Unit1 Leaf Name  \
 0                Nigeria Office
 1                Nigeria Office
 2                Nigeria Office
 3                Nigeria Office
 4                Nigeria Office
 ...                         ...
 85648            Tunisia Office
 85649            Tunisia Office
 85650            Tunisia Office
 85651            Tunisia Office
 85652        Francophone Region

                                          Broker Name  \
 0                      Gallagher Reinsurance Brokers
 1                      Gallagher Reinsurance Brokers
 2                      Gallagher Reinsurance Brokers
 3                      Gallagher Reinsurance Brokers
 4                      Gallagher Reinsurance Brokers
 ...                                              ...
 85648  ApEx Insurance Brokers
 85649  ApEx Insurance Brokers
 85650  ApEx Insurance Brokers
 85651  ApEx Insurance Brokers
 85652  Atlas Reinsurance Consultants (Tunisie)

                                             Insured Name Insured Period Start  \
 0                       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00
 1                       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00
 2             TOTAL UPSTREAM NIGERIA LIMITED (AKPO FPSO)  2023-04-01 00:00:00
 3      INDORAMA ELEME PETROCHEMICALS/FERTILIZERS LIMITED  2019-11-01 00:00:00
 4                 TOTAL UPSTREAM NIGERIA LIMITED (EGINA)  2023-12-02 00:00:00
 ...                                                  ...                  ...
 85648                                                NaN  2024-10-01 00:00:00
 85649                                                NaN  2024-10-01 00:00:00
 85650                                                NaN  2024-10-01 00:00:00
 85651                                                NaN  2024-10-01 00:00:00
 85652                                                NaN  2025-01-01 00:00:00

        ... Detail Amount (Original) Detail Amount (Base) Retroceded Amt Base  \
 0      ...                  1751.75              1751.75                0.00
 1      ...                   623.27               623.27                0.00
 2      ...                  1220.83              1220.83                0.00
 3      ...                  1049.96              1049.96                0.00
 4      ...                  2914.86              2914.86                0.00
 ...    ...                      ...                  ...                 ...
 85648  ...                 -1065.22              -195.56                0.00
 85649  ...                   -29.40                -5.40                0.00
 85650  ...                 -7257.60             -1332.38                0.00
 85651  ...                 -2713.21              -498.10                0.00
 85652  ...              -1586115.05             -2838.80                0.00

       Retained Amt Base Main Class of Business  \
 0               1751.75                Oil&Gas
 1                623.27                Oil&Gas
 2               1220.83                Oil&Gas
 3               1049.96                Oil&Gas
 4               2914.86                Oil&Gas
 ...                 ...                    ...
 85648           -195.56               Accident
 85649             -5.40               Property
 85650          -1332.38            Engineering
 85651           -498.10            Engineering
 85652          -2838.80              Financial

                          Class of Business      Registered Date  \
 0                         All Risk Oil&Gas  2024-05-08 06:24:35
 1                         All Risk Oil&Gas  2024-07-29 08:04:11
 2                         All Risk Oil&Gas  2024-05-08 06:31:34
 3                         All Risk Oil&Gas  2025-08-11 12:33:08
 4                         All Risk Oil&Gas  2024-05-08 08:01:50
 ...                                    ...                  ...
 85648                   Bailee's Liability  2025-11-25 08:32:41
 85649                            All Risks  2025-11-25 08:30:40
 85650  Contractors Plant & Machinery (CPM)  2025-11-25 08:24:03
 85651  Contractors Plant & Machinery (CPM)  2025-11-25 08:29:15
 85652                         General Bond  2026-01-06 13:41:45

                Closed Date WS Registered By           WS Closed By
 0      2024-05-08 09:20:25   Frances Nwogbe       Michael Adeyinka
 1      2024-07-29 08:05:30   Frances Nwogbe  Sandra Didiya Yakusak
 2      2024-05-08 09:20:05   Frances Nwogbe       Michael Adeyinka
 3      2025-08-11 12:37:22   Frances Nwogbe        Abigail Oyewole
 4      2024-05-08 09:19:30   Frances Nwogbe       Michael Adeyinka
 ...                    ...              ...                    ...
 85648  2025-11-25 15:48:09   Mohamed Rezgui              Ben Nader
 85649  2025-11-25 15:48:29   Mohamed Rezgui              Ben Nader
 85650  2025-11-25 15:48:22   Mohamed Rezgui              Ben Nader
 85651  2025-11-25 15:48:33   Mohamed Rezgui              Ben Nader
 85652  2026-01-06 14:29:24  Oumar Coulibaly        Laetitia Likane

 [85653 rows x 28 columns],
 'claimTable':       Business ID                                     Business Title  \
 0        NPF1205A              ZIMASCO (PVT) LTD, ZIMBABWE - PD + BI
 1        NPF1274A  VARIABLE MULTI-LINE DECLARATIONS (CORONATION I...
 2        NPF1286A                                              PRASA
 3        NPF1286A                                              PRASA
 4        NPF1295A                               KENMARE RESOURCE PLC
 ...           ...                                                ...
 34695    PPT6231A                      ASTREE ASSURANCE/NN MARINE QP
 34696    PPT6314A                           GLOBUS RE/SURPLUS/TREATY
 34697    PPT6314A                           GLOBUS RE/SURPLUS/TREATY
 34698    PPT6319A                     SUNU BURKINA./BOND QUOTA SHARE
 34699    PPT6319A                     SUNU BURKINA./BOND QUOTA SHARE

            Type of Business Underwriting Year  \
 0      Non-Prop Facultative              2021
 1      Non-Prop Facultative              2023
 2      Non-Prop Facultative              2022
 3      Non-Prop Facultative              2022
 4      Non-Prop Facultative              2022
 ...                     ...               ...
 34695   Proportional Treaty              2025
 34696   Proportional Treaty              2024
 34697   Proportional Treaty              2024
 34698   Proportional Treaty              2024
 34699   Proportional Treaty              2024

                                              Cedent Name  Cedent Country  \
 0          Zimnat Lion Insurance Company                        Zimbabwe
 1                               Coronation Insurance Plc         Nigeria
 2                                Rockstone Group Limited  United Kingdom
 3                                Rockstone Group Limited  United Kingdom
 4      BEST MERIDIAN INTERNATIONAL INSURANCE COMPANY SPC   United States
 ...                                                  ...             ...
 34695                                   Astree Assurance         Tunisia
 34696      GLOBUS-Re SA                                     Burkina Faso
 34697      GLOBUS-Re SA                                     Burkina Faso
 34698                             SUNU IARD Burkina Faso    Burkina Faso
 34699                             SUNU IARD Burkina Faso    Burkina Faso

       Reporting Unit1 Leaf Name                       Broker Name  \
 0           ZIMBABWE SUBSIDIARY                        Minerva Re
 1                Nigeria Office     Gallagher Reinsurance Brokers
 2           ZIMBABWE SUBSIDIARY  Arthur J. Gallagher (UK) Limited
 3           ZIMBABWE SUBSIDIARY  Arthur J. Gallagher (UK) Limited
 4           ZIMBABWE SUBSIDIARY             BESSO INSURANCE GROUP
 ...                         ...                               ...
 34695            Tunisia Office                               NaN
 34696        Francophone Region                               NaN
 34697        Francophone Region                               NaN
 34698        Francophone Region                     SUNU Services
 34699        Francophone Region                     SUNU Services

                                   Insured Name Insured Period Start  ...  \
 0                        ZIMASCO (PVT) LIMITED  2021-01-01 00:00:00  ...
 1      VARIABLE MULTI-LINE PACKAGE REINSURANCE  2023-12-16 00:00:00  ...
 2                                        PRASA  2022-04-01 00:00:00  ...
 3                                        PRASA  2022-04-01 00:00:00  ...
 4                        KENMARE RESOURCES PLC  2022-04-01 00:00:00  ...
 ...                                        ...                  ...  ...
 34695                                      NaN  2025-01-01 00:00:00  ...
 34696                                      NaN  2024-01-01 00:00:00  ...
 34697                                      NaN  2024-01-01 00:00:00  ...
 34698                                      NaN  2024-01-01 00:00:00  ...
 34699                                      NaN  2024-01-01 00:00:00  ...

       Detail Amount (Original) Detail Amount (Base) Retroceded Amt Base  \
 0                       -32.66               -32.66                0.00
 1                    -17500.00            -17500.00                0.00
 2                 -14601327.25           -819217.73                0.00
 3                    -22814.68             -1321.04                0.00
 4                   -374856.18           -374856.18                0.00
 ...                        ...                  ...                 ...
 34695                 24962.00              8645.06                0.00
 34696             -12755239.00            -22226.00                0.00
 34697              12755239.00             22226.00                0.00
 34698              28227272.50             49711.54                0.00
 34699             -28227272.50            -50289.30                0.00

       Retained Amt Base Main Class of Business   Class of Business  \
 0                -32.66               Property     Assets All Risk
 1             -17500.00                Oil&Gas    All Risk Oil&Gas
 2            -819217.73               Property     Assets All Risk
 3              -1321.04               Property     Assets All Risk
 4            -374856.18               Property   Fire (Commercial)
 ...                 ...                    ...                 ...
 34695           8645.06            Engineering      Contract Works
 34696         -22226.00               Property  Property All Risks
 34697          22226.00               Property  Property All Risks
 34698          49711.54              Financial        General Bond
 34699         -50289.30              Financial        General Bond

            Registered Date          Closed Date  WS Registered By  \
 0      2025-06-13 07:40:26  2025-06-13 07:55:47   Sandra Chivende
 1      2024-11-27 14:31:31  2024-11-27 14:36:07    Frances Nwogbe
 2      2024-09-24 13:58:17  2024-10-04 08:08:17  Godswill Kachiri
 3      2025-10-28 13:24:48  2025-10-28 14:03:26      Munashe Bope
 4      2025-01-07 09:07:33  2025-02-19 14:04:25   Sandra Chivende
 ...                    ...                  ...               ...
 34695  2025-09-02 07:53:47  2025-09-02 08:19:00    Mohamed Rezgui
 34696  2025-08-20 15:43:10  2025-08-20 15:47:16     Irie Laetitia
 34697  2025-08-21 14:35:39  2025-08-21 15:44:37     Irie Laetitia
 34698  2025-11-07 05:10:17  2025-11-11 14:05:30     Irie Laetitia
 34699  2025-09-03 01:21:50  2025-09-03 11:46:35     Irie Laetitia

             WS Closed By
 0      Banarbas Rondozai
 1        Abigail Oyewole
 2      Banarbas Rondozai
 3         Lisah Mazhindu
 4      Banarbas Rondozai
 ...                  ...
 34695          Ben Nader
 34696    Laetitia Likane
 34697    Laetitia Likane
 34698    Laetitia Likane
 34699    Laetitia Likane

 [34700 rows x 28 columns],
 'commissionTable':        Business ID                                     Business Title  \
 0         NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 1         NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 2         NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 3         NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 4         NPF1003A                   CHEVRON NIGERIA LTD/ESCRAVOS GTL
 ...            ...                                                ...
 123859    PPT6390A                    ARC/SERENITY SA/BOND/OPEN COVER
 123860    PPT6391A  PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...
 123861    PPT6391A  PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...
 123862    PPT6391A  PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...
 123863    PPT6391A  PEOPLE & PARTNERS PROPERTY AUTO FAC - BANYAN E...

             Type of Business Underwriting Year  \
 0       Non-Prop Facultative              2023
 1       Non-Prop Facultative              2023
 2       Non-Prop Facultative              2023
 3       Non-Prop Facultative              2023
 4       Non-Prop Facultative              2023
 ...                      ...               ...
 123859   Proportional Treaty              2025
 123860   Proportional Treaty              2025
 123861   Proportional Treaty              2025
 123862   Proportional Treaty              2025
 123863   Proportional Treaty              2025

                                           Cedent Name Cedent Country  \
 0                           NEM Insurance PLC Nigeria        Nigeria
 1                           NEM Insurance PLC Nigeria        Nigeria
 2                           NEM Insurance PLC Nigeria        Nigeria
 3                           NEM Insurance PLC Nigeria        Nigeria
 4                           NEM Insurance PLC Nigeria        Nigeria
 ...                                               ...            ...
 123859  Serenity S.A.                                    Ivory coast
 123860              People and Partners Insurance Plc       Cambodia
 123861              People and Partners Insurance Plc       Cambodia
 123862              People and Partners Insurance Plc       Cambodia
 123863              People and Partners Insurance Plc       Cambodia

        Reporting Unit1 Leaf Name  \
 0                 Nigeria Office
 1                 Nigeria Office
 2                 Nigeria Office
 3                 Nigeria Office
 4                 Nigeria Office
 ...                          ...
 123859        Francophone Region
 123860                      Asia
 123861                      Asia
 123862                      Asia
 123863                      Asia

                                           Broker Name  \
 0                       Gallagher Reinsurance Brokers
 1                       Gallagher Reinsurance Brokers
 2                       Gallagher Reinsurance Brokers
 3                       Gallagher Reinsurance Brokers
 4                       Gallagher Reinsurance Brokers
 ...                                               ...
 123859  Atlas Reinsurance Consultants (Tunisie)
 123860                                            NaN
 123861                                            NaN
 123862                                            NaN
 123863                                            NaN

                             Insured Name Insured Period Start  ...  \
 0       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00  ...
 1       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00  ...
 2       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00  ...
 3       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00  ...
 4       CHEVRON NIGERIA LTD/ESCRAVOS GTL  2023-01-02 00:00:00  ...
 ...                                  ...                  ...  ...
 123859                               NaN  2025-01-01 00:00:00  ...
 123860                               NaN  2025-10-01 00:00:00  ...
 123861                               NaN  2025-10-01 00:00:00  ...
 123862                               NaN  2025-10-01 00:00:00  ...
 123863                               NaN  2025-10-01 00:00:00  ...

        Detail Amount (Original) Detail Amount (Base) Retroceded Amt Base  \
 0                       -175.18              -175.18                0.00
 1                       -262.76              -262.76                0.00
 2                        -93.49               -93.49                0.00
 3                        -93.49               -93.49                0.00
 4                        -10.00               -10.00                0.00
 ...                         ...                  ...                 ...
 123859                -52323.38               -93.65                0.00
 123860                  -280.38              -280.38                0.00
 123861                   -62.94               -62.94                0.00
 123862                   -40.29               -40.29                0.00
 123863                    -9.05                -9.05                0.00

        Retained Amt Base Main Class of Business   Class of Business  \
 0                -175.18                Oil&Gas    All Risk Oil&Gas
 1                -262.76                Oil&Gas    All Risk Oil&Gas
 2                 -93.49                Oil&Gas    All Risk Oil&Gas
 3                 -93.49                Oil&Gas    All Risk Oil&Gas
 4                 -10.00                Oil&Gas    All Risk Oil&Gas
 ...                  ...                    ...                 ...
 123859            -93.65              Financial        General Bond
 123860           -280.38               Property  Fire (unspecified)
 123861            -62.94               Property  Fire (unspecified)

In [33]:
def ratioAnalysis(tableDict : dict, filterArray = None):
    
    resultTableDictionary = {
    categoryHeader:np.append(np.array(filterItems), "Total"),
    "Net Premium": np.array([]),
    "Net Incurred Claim": np.array([]),
    "Net Commission": np.array([]),
    "Net Technical Margin": np.array([]),
    "Loss Ratio": np.array([]),
    "Commission Ratio": np.array([]),
    "Net Management Expense Ratio": np.array([]),
    "Net Technical Margin Ratio": np.array([]),
    "Net Retro Expense Ratio": np.array([]),
    "Combined Ratio": np.array([])
    }

    grossPremiumSum = 0
    grossPremiumSumArr = np.array([])

    premiumTable = tableDict["premiumTable"]
    claimTable =  tableDict["claimTable"]
    commissionTable =  tableDict["commissionTable"]

    def modifyTable(filterLabel,filterItem, operation = "Equal"):
         
        nonlocal premiumTable, claimTable, commissionTable
        if operation == "Equal":
            premiumTable = premiumTable[premiumTable[filterLabel] == filterItem]
            claimTable = claimTable[claimTable[filterLabel] == filterItem]
            commissionTable = commissionTable[commissionTable[filterLabel] == filterItem]
        elif operation == "Atlest":
            premiumTable = premiumTable[premiumTable[filterLabel] >= filterItem]
            claimTable = claimTable[claimTable[filterLabel] >= filterItem]
            commissionTable = commissionTable[commissionTable[filterLabel]>= filterItem]
        elif operation == "Atmost":
            premiumTable = premiumTable[premiumTable[filterLabel] <= filterItem]
            claimTable = claimTable[claimTable[filterLabel] <= filterItem]
            commissionTable = commissionTable[commissionTable[filterLabel]<= filterItem]

    for item in filterItems:
        modifyTable(categoryHeader,item)

        if filterArray and len(filterArray) > 0:
            for filter_spec in filterArray:
                header = filter_spec[0]
                filterValue = filter_spec[1]
                operation = filter_spec[2]
                modifyTable(header, filterValue, operation)
                # if operation == "Equal":
                #     modifyTable(header, filterValue)
                # elif operation == "Atlest":
                #     modifyTable(header, filterValue, "Atlest")
                # elif operation == "Atmost":
                #     modifyTable(header, filterValue, "Atmost")

        premiumSum = np.sum(premiumTable[dataFieldHeader])
        grossPremiumSum = np.sum(premiumTable[grossDataFieldHeader])
        print(grossPremiumSum)
        claimSum = np.sum(claimTable[dataFieldHeader])
        commissionSum = np.sum(commissionTable[dataFieldHeader])

        netTechnicalMargin = premiumSum + claimSum + commissionSum
        lossRatio = abs(claimSum / premiumSum) if premiumSum != 0 else 0
        commissionRatio = abs(commissionSum / premiumSum) if premiumSum != 0 else 0
        netManagementExpenseRatioLocal = netManagementExpenseRatio
        netTechnicalMarginRatio = abs(netTechnicalMargin/premiumSum) if premiumSum != 0 else 0
        netRetroExpenseRatio = 1 - (premiumSum / grossPremiumSum) if grossPremiumSum != 0 else 0
        combinedRatio = lossRatio + commissionRatio + netManagementExpenseRatio + netRetroExpenseRatio

        resultTableDictionary["Net Premium"]= np.append(resultTableDictionary["Net Premium"], premiumSum)
        resultTableDictionary["Net Incurred Claim"] = np.append(resultTableDictionary["Net Incurred Claim"], claimSum)
        resultTableDictionary["Net Commission"] = np.append(resultTableDictionary["Net Commission"], commissionSum)
        resultTableDictionary["Net Technical Margin"] = np.append(resultTableDictionary["Net Technical Margin"], netTechnicalMargin)
        resultTableDictionary["Loss Ratio"] = np.append(resultTableDictionary["Loss Ratio"],lossRatio)
        resultTableDictionary["Commission Ratio"] = np.append(resultTableDictionary["Commission Ratio"], commissionRatio)
        resultTableDictionary["Net Management Expense Ratio"] = np.append(resultTableDictionary["Net Management Expense Ratio"], netManagementExpenseRatioLocal)
        resultTableDictionary["Net Technical Margin Ratio"] = np.append(resultTableDictionary["Net Technical Margin Ratio"], netTechnicalMarginRatio)
        resultTableDictionary["Net Retro Expense Ratio"]= np.append(resultTableDictionary["Net Retro Expense Ratio"], netRetroExpenseRatio)
        resultTableDictionary["Combined Ratio"] = np.append(resultTableDictionary["Combined Ratio"], combinedRatio)
        grossPremiumSumArr = np.append(grossPremiumSumArr,grossPremiumSum)

        premiumTable = tableDict["premiumTable"]
        claimTable =  tableDict["claimTable"]
        commissionTable =  tableDict["commissionTable"]
    
    resultTableDictionary["Net Premium"]= np.append(resultTableDictionary["Net Premium"], np.sum(resultTableDictionary["Net Premium"]))
    resultTableDictionary["Net Incurred Claim"]= np.append(resultTableDictionary["Net Incurred Claim"], np.sum(resultTableDictionary["Net Incurred Claim"]))
    resultTableDictionary["Net Commission"]= np.append(resultTableDictionary["Net Commission"], np.sum(resultTableDictionary["Net Commission"]))
    resultTableDictionary["Net Technical Margin"]= np.append(resultTableDictionary["Net Technical Margin"], np.sum(resultTableDictionary["Net Technical Margin"]))

    resultTableDictionary["Loss Ratio"] = np.append(resultTableDictionary["Loss Ratio"],
                                                abs((resultTableDictionary["Net Incurred Claim"])[-1]
                                                    /(resultTableDictionary["Net Premium"])[-1]) )
    resultTableDictionary["Commission Ratio"] = np.append(resultTableDictionary["Commission Ratio"],
                                                abs((resultTableDictionary["Net Commission"])[-1]
                                                    /(resultTableDictionary["Net Premium"])[-1]) )
    resultTableDictionary["Net Management Expense Ratio"] = np.append(resultTableDictionary["Net Management Expense Ratio"], netManagementExpenseRatio )
    resultTableDictionary["Net Technical Margin Ratio"] = np.append(resultTableDictionary["Net Technical Margin Ratio"],
                                                abs((resultTableDictionary["Net Technical Margin"])[-1]
                                                    /(resultTableDictionary["Net Premium"])[-1]) )
    resultTableDictionary["Net Retro Expense Ratio"] = np.append(resultTableDictionary["Net Retro Expense Ratio"],1 -
                                                abs((resultTableDictionary["Net Premium"])[-1]
                                                    /np.sum(grossPremiumSumArr)) )
    resultTableDictionary["Combined Ratio"] = np.append(resultTableDictionary["Combined Ratio"],
                                                        resultTableDictionary["Loss Ratio"][-1] + resultTableDictionary["Commission Ratio"][-1] +\
                                                            resultTableDictionary["Net Management Expense Ratio"][-1] + resultTableDictionary["Net Retro Expense Ratio"][-1])
    
    resultTable = pd.DataFrame(resultTableDictionary).reset_index(drop=True)

    # ratio_columns = [
    # "Loss Ratio",
    # "Commission Ratio",
    # "Net Management Expense Ratio",
    # "Net Technical Margin Ratio",
    # "Net Retro Expense Ratio",
    # "Combined Ratio"
    # ]

    # name_columns = [
    #     "Net Premium",
    #     "Net Incurred Claim",
    #     "Net Commission",
    #     "Net Technical Margin"
    # ]

    # resultTable[name_columns] = resultTable[name_columns].map(
    #     lambda x: f"({abs(x):,.2f})" if x < 0 else f"{x:,.2f}"
    # )

    # resultTable[ratio_columns] = resultTable[ratio_columns].map(lambda x: f"{x:.2%}")
    return resultTable

filterArr = [['Main Class of Business', 'Accident', 'Equal']]
resultTable = ratioAnalysis(tableDict,filterArr)
resultTable

2906243.894966
2335775.496796994
20399294.425018974
20636886.87832202
291868.913832
317471.4947509999
327704.756025
6823580.468460005
600000.0
552565.302816
153673.154319
159096.56
2885.726612
4637234.573103998

,Reporting Unit1 Leaf Name,Net Premium,Net Incurred Claim,Net Commission,Net Technical Margin,Loss Ratio,Commission Ratio,Net Management Expense Ratio,Net Technical Margin Ratio,Net Retro Expense Ratio,Combined Ratio
0,Nigeria Office,2813108.69,-826964.26,-887586.22,1098558.20,0.29,0.32,0.12,0.39,0.03,0.76
1,Tunisia Office,2334700.30,-302740.05,-566495.89,1465464.36,0.13,0.24,0.12,0.63,0.00,0.49
2,ZIMBABWE SUBSIDIARY,20354157.83,-5809196.50,-6909627.95,7635333.38,0.29,0.34,0.12,0.38,0.00,0.75
3,KENYA SUBSIDIARY,19463619.73,-10945618.01,-5940067.50,2577934.22,0.56,0.31,0.12,0.13,0.06,1.04
4,Africa,291868.91,-318694.37,-80425.42,-107250.87,1.09,0.28,0.12,0.37,0.00,1.49
5,Asia,317471.49,-7649.50,-89740.68,220081.32,0.02,0.28,0.12,0.69,0.00,0.43
6,MiddleEast,327704.76,-63425.20,-94461.52,169818.04,0.19,0.29,0.12,0.52,0.00,0.60
7,Ghana Office,4759624.25,-541045.87,-1646480.73,2572097.65,0.11,0.35,0.12,0.54,0.30,0.88
8,Latin America,600000.00,0.00,-165000.00,435000.00,0.00,0.28,0.12,0.72,0.00,0.40
9,Sierra Leone Office,552565.30,-6983.46,-185802.54,359779.30,0.01,0.34,0.12,0.65,0.00,0.47
10,Gambia Office,153673.15,-96027.14,-40422.21,17223.80,0.62,0.26,0.12,0.11,0.00,1.01
11,Liberia Office,159096.56,-27726.90,-53012.17,78357.49,0.17,0.33,0.12,0.49,0.00,0.63
12,Anglophone Region,2885.73,89265.60,-691.12,91460.20,30.93,0.24,0.12,31.69,0.00,31.29
13,Francophone Region,3873471.09,-297040.55,-1238309.14,2338121.40,0.08,0.32,0.12,0.60,0.16,0.68
14,Total,56003947.80,-19153846.21,-17898123.11,18951978.48,0.34,0.32,0.12,0.34,0.07,0.85

In [40]:

previousTableLength = 0
wb = xl.Workbook("try.xlsx")
ws = wb.add_worksheet("table")

def addTable(ws,oneSheet = True):
    global previousTableLength

    verticalDis = 3
    tableList = resultTable.values.tolist()
    columns = [{"header": col} for col in resultTable.columns.tolist()]

    num_rows = len(resultTable)
    num_cols = len(resultTable.columns)

    start_row = previousTableLength + verticalDis 
    start_col = 1

    end_row = start_row + num_rows
    end_col = start_col + num_cols - 1

    start_col_letter = xl_col_to_name(start_col)
    end_col_letter = xl_col_to_name(end_col)

    
    table_range = f"{start_col_letter}{start_row}:{end_col_letter}{end_row}"
    if oneSheet:
        previousTableLength += end_row

    ws.write(f"{start_col_letter}{start_row-1}", "Hello")
    ws.add_table(table_range, {
        "data": tableList,
        "columns": columns
    })

for i in [1,2]:
    addTable(ws)

wb.close()

In [ ]:

def excelSheetsGenerator(analysisType,
                         categoryBundle,
                         oneSheet = True):

    output = io.BytesIO()
    workBook = xl.Workbook(output, {'in_memory': True})


    previousTableLength = 0
    def addTable(ws, table, category = None):

        verticalDis = 2
        
        tableList = table.values.tolist()
        columns = [{"header": col} for col in table.columns.tolist()]

        num_rows = len(table)
        num_cols = len(table.columns)

        start_row = previousTableLength + verticalDis 
        start_col = 1

        end_row = start_row + num_rows
        end_col = start_col + num_cols - 1

        start_col_letter = xl_col_to_name(start_col)
        end_col_letter = xl_col_to_name(end_col)

        
        table_range = f"{start_col_letter}{start_row}:{end_col_letter}{end_row}"
        if oneSheet:
            ws.write(f"{start_col_letter}{start_row-1}", str(category))
            previousTableLength += end_row

        ws.add_table(table_range, {
            "data": tableList,
            "columns": columns
        })


    if oneSheet:
        workSheet = workBook.add_worksheet(analysisFunParem["analysis type"])
        for category in categoryBundle:
            resultTable =  performanceAnalysis()
            addTable(workSheet, resultTable, category)

            workBook.close()
            output.seek(0)
    else:
        for category in categoryBundle:
            workSheet = workBook.add_worksheet(str(category)[0:min(30,len(category))])
            resultTable =  performanceAnalysis()
            addTable(workSheet, resultTable)

            workBook.close()
            output.seek(0)

IndentationError: expected an indented block after 'for' statement on line 12 (378029798.py, line 14)

In [42]:
b = "sekou"
b[0:min(2,5)]

'se'

In [3]:
import xlsxwriter as xl

wb = xl.Workbook("try.xlsx")
ws = wb.add_worksheet("table")

ws.add_table("A1:B3", {
    "data": [
        ["Alice", 90],
        ["Bob", 85]
    ],
    "columns": [
        {"header": "Name"},
        {"header": "Score"}
    ]
})

wb.close()  # ← THIS is critical

In [26]:
resultTable.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['Reporting Unit1 Leaf Name', 'Net Premium', 'Net Incurred Claim',
       'Net Commission', 'Net Technical Margin', 'Loss Ratio',
       'Commission Ratio', 'Net Management Expense Ratio',
       'Net Technical Margin Ratio', 'Net Retro Expense Ratio',
       'Combined Ratio'],
      dtype='str')>

In [4]:
arr = range(3,7)
np.array(arr)

array([3, 4, 5, 6])